### ISSUE TITLE
Preheat page does not work

### ISSUE THREAD

**Issue by MatejPavel** [jadonmmiller/UltimateDuetMenuSystem#2] opened 2021-03-12 17:33 UTC
Like the title says, the preheat page is all jumbled up and does nothing. The only way to return from it is resetting the machine.

**Comment by jadonmmiller** [comment] 2021-03-12 18:52
Unfortunately, I've noticed the same thing. It seems like a firmware issue. I've posted it on the [Duet Forums](https://forum.duet3d.com/topic/22097/12864-display-unresponsive-on-preheat-page) and we'll see what they say.

Until then, a workaround is to make a preheat macro and just use that. The macros page should still be fully functional.

Thanks for reporting that!
Jadon

**Comment by jadonmmiller** [comment] 2021-04-23 10:33
David Crocker has confirmed that although this was caused by a picture on the preheat page overflowing off the screen, the firmware should account for that and not crash. See the forum post linked above for more information. This should be fixed in RRF firmware version 3.3beta3 and onward.

**Closed by jadonmmiller** 2021-04-23 10:33 UTC
